# Generated by Django 5.0.7 on 2025-01-07 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aptitude', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together={('user', 'problem')},
        ),
    ]
