# Generated by Django 5.0.7 on 2025-01-29 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptitude', '0002_alter_useranswer_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='answerurl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
