# Generated by Django 5.0.7 on 2025-02-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptitude', '0005_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='hired_last_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
