# Generated by Django 5.0.7 on 2025-03-21 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptitude', '0006_company_description_company_hired_last_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='test_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
