# Generated by Django 5.0.7 on 2025-03-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptitude', '0007_problem_test_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='questionimage',
            field=models.URLField(blank=True, null=True),
        ),
    ]
