# Generated by Django 5.0.7 on 2025-03-22 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptitude', '0008_problem_questionimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(max_length=1)),
                ('solution_image_url', models.URLField(blank=True, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('time_solved', models.DateTimeField(auto_now_add=True)),
                ('test_id', models.IntegerField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aptitude.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
