# Generated by Django 5.0.7 on 2025-04-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptitude', '0013_customuser_branch_customuser_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
