# Generated by Django 5.0.7 on 2025-04-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptitude', '0014_alter_customuser_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
