# Generated by Django 5.0.7 on 2025-07-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptitude', '0015_problem_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_batch', models.IntegerField()),
                ('company_name', models.CharField(max_length=255)),
                ('role_offered', models.CharField(max_length=255)),
                ('ctc', models.CharField(max_length=100)),
                ('min_percent', models.FloatField()),
                ('min_cgpa', models.FloatField()),
                ('total_backlog', models.IntegerField()),
                ('active_backlog', models.IntegerField()),
                ('description', models.CharField(max_length=2000)),
                ('apply_link', models.URLField()),
                ('deadline', models.DateTimeField()),
                ('logo_url', models.URLField()),
                ('class12_10_percent', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_backlogs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cgpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='class10_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='class12_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sem1_sgpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sem2_sgpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sem3_sgpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sem4_sgpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sem5_sgpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sem6_sgpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sem7_sgpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sem8_sgpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_backlogs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
