# Generated by Django 5.0.7 on 2025-07-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptitude', '0016_placementcompany_customuser_active_backlogs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placementcompany',
            name='active_backlog',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='placementcompany',
            name='total_backlog',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
