# Generated by Django 5.0.7 on 2025-07-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptitude', '0017_alter_placementcompany_active_backlog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placementcompany',
            name='active_backlog',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='placementcompany',
            name='total_backlog',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
