# Generated by Django 5.0.7 on 2025-07-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptitude', '0018_alter_placementcompany_active_backlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementcompany',
            name='branches',
            field=models.CharField(blank=True, help_text='Comma-separated branches (e.g. IT,CSE)', max_length=100),
        ),
        migrations.AlterField(
            model_name='placementcompany',
            name='active_backlog',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='placementcompany',
            name='total_backlog',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
