# Generated by Django 5.0.7 on 2025-07-21 18:36

import django.db.models.deletion
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptitude', '0020_alter_placementcompany_active_backlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='student_class',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placementcompany',
            name='generate_form',
            field=models.BooleanField(default=False, help_text='Generate application form for this company'),
        ),
        migrations.AlterField(
            model_name='placementcompany',
            name='branches',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('IT', 'IT'), ('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ICE', 'ICE')], max_length=18),
        ),
        migrations.CreateModel(
            name='PlacementApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('enrollment_number', models.CharField(max_length=100)),
                ('student_class', models.IntegerField(blank=True, null=True)),
                ('cgpa', models.FloatField(blank=True, null=True)),
                ('total_percentage', models.FloatField(blank=True, null=True)),
                ('resume_link', models.URLField()),
                ('github_link', models.URLField(blank=True)),
                ('linkedin_link', models.URLField(blank=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aptitude.placementcompany')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('company', 'user')},
            },
        ),
    ]
