# Generated by Django 5.0.7 on 2025-07-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptitude', '0021_customuser_name_customuser_student_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='enrollment_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
